name: Enforce Develop to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is develop
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Error: Pull requests to main must be from the develop branch."
            exit 1
          fi
